<?php

require_once 'MyCavariaIndividual.php';
require_once 'MyCavariaOrganization.php';

function mijncavaria_menu() {
	$items = array();

	$items['mijncavaria'] = array(
		'title' => t('Mijn Cavaria'),
		'page callback' => 'mijncavaria_organizations_page',
		'access callback' => 'user_is_logged_in',
		'description' => t('my organizations'),
		'type' => MENU_CALLBACK,
    'file' => 'mijncavaria_organization_list.inc',
	);

  $items['mijncavaria_wijzigorganisatie'] = array(
    'title' => t('Mijn cavaria'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mijncavaria_organization_form'),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_CALLBACK,
    'file' => 'mijncavaria_organization.inc',
  );

	return $items;
}

